I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 52, in script
    e "You've created a newish Ren'Py game."
TypeError: 'int' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 52, in script
    e "You've created a newish Ren'Py game."
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\character.py", line 842, in do_display
    **display_args)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\core.py", line 3518, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\screen.py", line 714, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\layout.py", line 998, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\behavior.py", line 962, in event
    return handle_click(self.clicked)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\behavior.py", line 897, in handle_click
    rv = run(action)
  File "C:\Users\Qrow99\Documents\renpy-7.3.3-sdk\renpy\display\behavior.py", line 320, in run
    return action(*args, **kwargs)
TypeError: 'int' object is not callable

Windows-8-6.2.9200
Ren'Py 7.3.3.568
MAKE SOME HECKING COFFEE 1.0
Sat Oct 19 22:54:18 2019
